version: '3.7'

services:
    kibana:
        container_name: kibana
        image: kibana:7.17.12
        environment:
          - ELASTICSEARCH_HOSTS=http://vm-3:9200
        ports:
          - 5601:5601
