---
- name: Сервер Elasicsearch
  hosts: elk
  gather_facts: true
  become: true
  become_method: sudo

  tasks:

  - name: Install a .deb package from the internet
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb

  - name: Install a list of packages
    apt:
      update_cache: yes
      pkg:
      - docker
      - docker-compose
      - zabbix-agent2
      - zabbix-agent2-plugin-*

  - name: Add kvm module
    community.general.modprobe:
     name: kvm
     state: present

  - name: Creates /home/user/config
    file:
     path: "{{ item }}" 
     state: directory
    with_items:
     - '/home/user/config'
     - '/home/user/config/pipeline' 
  
  - name: Copy file 
    copy:
     src: config/logstash.yml
     dest: /home/user/config/logstash.yml
 
  - name: копирование my.conf
    copy:
     src: config/my.conf
     dest: /home/user/config/pipeline/my.conf

  - name: копирование elastic.yaml
    copy:
     src: config/elastic.yaml
     dest: /home/user/docker-compose.yaml
     remote_src: false
  
  - name: Create and start services
    community.docker.docker_compose:
     project_src: /home/user
     state: present
    
  - name: Правим /etc/zabbix/zabbix-agent2.conf
    replace:
     path:  /etc/zabbix/zabbix_agent2.conf
     regexp: 'Server=127.0.0.1'
     replace: 'Server=vm-5'
  
  - name: Restart service zabbix-agent2
    service:
      name: zabbix-agent2
      state: restarted
      enabled: yes
  
