---
- name: Scale the web service to 2
  hosts: zabbix-server
  gather_facts: true
  become: true
  become_method: sudo
  tasks:

  - name: Install a .deb package from the internet
    apt:
      deb: https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb

  - name: Install a list of packages
    apt:
      pkg:
       - pip
       - postgresql
       - zabbix-server-pgsql
       - zabbix-frontend-php
       - php7.4-pgsql
       - zabbix-nginx-conf
       - zabbix-sql-scripts
       - zabbix-agent
      update_cache: yes
  
  - name: Make sure psycopg2 is installed
    pip:
      name: psycopg2-binary
      state: present

  - name: Правим pg_hba.conf peer 1
    replace:
     path:  /etc/postgresql/13/main/pg_hba.conf
     regexp: 'local   all             postgres                                peer'
     replace: 'local   all             postgres                                md5'

  - name: Правим pg_hba.conf peer 2
    replace:
     path:  /etc/postgresql/13/main/pg_hba.conf
     regexp: 'host    all             all             127.0.0.1/32            md5'
     replace: 'host    all             all             127.0.0.1/32            trust'  


  - name: Start service httpd, if not started
    service:
     name: postgresql
     state: restarted

  - name: Create postgres user for my app
    community.postgresql.postgresql_user:
      login_user: "postgres"
      login_password: ""
      login_host: "127.0.0.1"
      name: zabbix
      password: "12345678"

  - name: Create a new database with name "acme"
    community.postgresql.postgresql_db:
      login_user: "postgres"
      login_password: ""
      login_host: "127.0.0.1"
      name: zabbix
      owner: zabbix

  - name: This command will change the working directory to somedir/
    shell:
      cmd: zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

  - name: Правим /etc/zabbix/zabbix_server.conf 
    replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '# DBPassword=password'
      replace: 'DBPassword=12345678' 

  - name: Правим /etc/zabbix/nginx.conf
    replace:
     path:  /etc/zabbix/nginx.conf
     regexp: '#        listen          8080;'
     replace: 'listen 8080;'

  - name: Правим /etc/zabbix/nginx.conf
    replace:
     path:  /etc/zabbix/nginx.conf
     regexp: '#        server_name     example.com;'
     replace: 'server_name test.local;' 
  
  - name: Правим pg_hba.conf peer 3
    replace:
     path:  /etc/postgresql/13/main/pg_hba.conf
     regexp: 'host    all             all             127.0.0.1/32            trust'
     replace: 'host    all             all             127.0.0.1/32            md5' 
   
  - name: Правим pg_hba.conf peer 1
    replace:
     path:  /etc/postgresql/13/main/pg_hba.conf
     before: '# TYPE  DATABASE        USER            ADDRESS                 METHOD'
     regexp: 'local   all             postgres                                md5'
     replace: 'local   all             postgres                                peer'

 

  - name: "Restart service zabbix-server"
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - zabbix-server
      - nginx
      - php7.4-fpm